INSERT INTO FILM_RATING (RATING_NAME) VALUES ('G');
INSERT INTO FILM_RATING (RATING_NAME) VALUES ('PG');
INSERT INTO FILM_RATING (RATING_NAME) VALUES ('PG-13');
INSERT INTO FILM_RATING (RATING_NAME) VALUES ('R');
INSERT INTO FILM_RATING (RATING_NAME) VALUES ('NC-17');

INSERT INTO GENRES (GENRE_NAME) VALUES ('Комедия');
INSERT INTO GENRES (GENRE_NAME) VALUES ('Драма');
INSERT INTO GENRES (GENRE_NAME) VALUES ('Мультфильм');
INSERT INTO GENRES (GENRE_NAME) VALUES ('Триллер');
INSERT INTO GENRES (GENRE_NAME) VALUES ('Документальный');
INSERT INTO GENRES (GENRE_NAME) VALUES ('Боевик');